server:
  port: ${CUSTOM.SERVER.PORT:8090}

### Circuitbreaker configuration
resilience4j:
 circuitbreaker:
   configs:
     customConfig:
       sliding-window-size: 25
       failure-rate-threshold: 50
       wait-duration-in-open-state: 60s
       permitted-number-of-calls-in-half-open-state: 10
       slow-call-rate-threshold: 50
       slow-call-duration-threshold: 2s
   instances:  
     product-service-cb:
       base-config: customConfig
 timelimiter:
   configs:
     customConfig:
       timeout-duration: 2s
   instances:
     product-service-cb:
       base-config: customConfig

### Eureka Client configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA.HOST.SERVER:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    refresh:
      enable: true

### Cloud Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args: 
                name: product-service-cb
                statusCodes: 500, 404
            #- MitocodeFilter=HEADER_KEY,HEADER_VALUE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: authentication-server
          uri: lb://authentication-server-jwt
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2

config:
  security:
    privateKey: 2605f66d54d843b33263ac196066b036c877eb31336b531706afee45a235331720311da58d61764ddea76d3174b78e2a1724087206e071d1fff6eae1f462b404c0548e2a025475042df81182d3c0af4be355077cc8649f6937afd42aa7f4a01233745e169f82a49855ad9ecbe10738c00ac6b4fd2cab66e1b6c26b54ea0e8e28

### Actuator info (/actuator/info)
info:
  app:
    app-name: Cloud Gateway Microservice
    description: Microservicio para el ruteo de los microservicios
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator