server:
  port: ${CUSTOM.SERVER.PORT:9004}

encrypt:
  key: mitocode-secrets

### Eureka Client configuration
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA.HOST.SERVER:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    refresh:
      enable: true

### Actuator info (/actuator/info)
info:
  app:
    app-name: User Service Microservice Desarrollo
    description: Microservicio para el crud de los usuarios
    version: 1.0

### Mongo database configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: '{cipher}50187c298f2eb7007a9af9b891cef19e95656af635d7512be5ada3e6ed622d09'
      username: '{cipher}15dfd68adfe32e63d2ef16b7e1b0b090c7c1a39c824656c1010db7870dd49b04'
      password: '{cipher}225d9814e6187bd8ab890c72d08bd557185cb3e783a23efec8bff01c030b3172'
      uri: mongodb://mitocode:mitocode@localhost:27017
      authentication-database: admin

management:
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping, memory, mem
          show-component: always
          show-details: always
  info:
    env:
      enabled: true
  health:
    env:
      enabled: true